{% set version = "18.9.0" %}

package:
  name: cherrypy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/C/CherryPy/CherryPy-{{ version }}.tar.gz
  sha256: 6b06c191ce71a86461f30572a1ab57ffc09f43143ba8e42c103c7b3347220eb1

build:
  number: 0
  skip: true  # [py<36 or s390x]
  entry_points:
    - cherryd = cherrypy.__main__:run
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools_scm >=3.5
    - toml
    - wheel
  run:
    - python
    - cheroot >=8.2.1
    - portend >=2.1.1
    - more-itertools
    - zc.lockfile
    - jaraco.collections
    - pywin32 >=227   # [win and py<310]
    - importlib-metadata # [py<38]
  run_constrained:
    - simplejson
    - routes >=2.3.1
    - pyopenssl

test:
  imports:
    - cherrypy
    - cherrypy.lib
    - cherrypy.process
    - cherrypy.scaffold
    - cherrypy.test
    - cherrypy.tutorial
  commands:
    - pip check
    - cherryd -h
  requires:
    - pip

about:
  home: https://cherrypy.dev
  license: BSD-3-Clause
  license_file: LICENSE.md
  license_family: BSD
  summary: Object-Oriented HTTP framework
  description: |
    CherryPy is a pythonic, object-oriented web framework.
    It allows developers to build web applications in much the same way they would
    build any other object-oriented Python program. This results in smaller source
    code developed in less time.
  dev_url: https://github.com/cherrypy/cherrypy
  doc_url: https://docs.cherrypy.dev

extra:
  recipe-maintainers:
    - pmlandwehr
    - carlodri
