{% set version = "6.1.1" %}
package:
  name: cherrypy
  version: {{ version }}

source:
  fn: CherryPy-{{ version }}.tar.gz
  url: https://github.com/cherrypy/cherrypy/archive/v{{ version }}.tar.gz
  sha256: 15a34242cbc0464467c0dc75b65b887002e9c294530ae68b8daef268cfa21dd2

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - six

  run:
    - python
    - six

test:
  imports:
    - cherrypy
    - cherrypy.lib
    - cherrypy.process
    - cherrypy.scaffold
    - cherrypy.test
    - cherrypy.tutorial
    - cherrypy.wsgiserver

about:
  home: http://www.cherrypy.org
  license: BSD 3-Clause
  summary: 'Object-Oriented HTTP framework'

extra:
  recipe-maintainers:
    - pmlandwehr
