{% set name = "CherryPy" %}
{% set version = "14.2.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "d793223398ea62206f1ac1e98e4f6a7e2fda588fb78afb3774c3dae00888ac5c" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  entry_points:
    - cherryd = cherrypy.__main__:run
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools_scm

  run:
    - python
    - setuptools
    - six >=1.11.0
    - cheroot >=6.2.4
    - portend >=2.1.1
    - pywin32   # [win]

test:
  imports:
    - cherrypy
    - cherrypy.lib
    - cherrypy.process
    - cherrypy.scaffold
    - cherrypy.test
    - cherrypy.tutorial

  commands:
    - cherryd -h

about:
  home: http://www.cherrypy.org
  license: BSD 3-Clause
  license_file: LICENSE.md
  license_family: BSD
  summary: 'Object-Oriented HTTP framework'
  description: |
    CherryPy is a pythonic, object-oriented web framework.
    It allows developers to build web applications in much the same way they would
    build any other object-oriented Python program. This results in smaller source
    code developed in less time.
  dev_url: https://github.com/cherrypy/cherrypy
  doc_url: http://docs.cherrypy.org/en/latest
  doc_source_url: https://github.com/cherrypy/cherrypy/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - pmlandwehr
