{% set name = "CherryPy" %}
{% set version = "15.0.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "7404638da9cf8c6be672505168ccb63e16d33cb3aa16a02ec30a44641f7546af" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  entry_points:
    - cherryd = cherrypy.__main__:run
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - setuptools_scm

  run:
    - python
    - setuptools
    - six >=1.11.0
    - cheroot >=6.2.4
    - portend >=2.1.1
    - jaraco.classes

test:
  imports:
    - cherrypy
    - cherrypy.lib
    - cherrypy.process
    - cherrypy.scaffold
    - cherrypy.test
    - cherrypy.tutorial

  commands:
    - cherryd -h

about:
  home: http://www.cherrypy.org
  license: BSD 3-Clause
  license_file: LICENSE.md
  license_family: BSD
  summary: 'Object-Oriented HTTP framework'
  dev_url: https://github.com/cherrypy/cherrypy
  doc_url: http://docs.cherrypy.org/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
