{% set name = "CherryPy" %}
{% set version = "18.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 48de31ba3db04c5354a0fcf8acf21a9c5190380013afca746d50237c9ebe70f0

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - cherryd = cherrypy.__main__:run
  skip: True  # [py27 or py34]

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - more-itertools
    - cheroot >=6.2.4
    - portend >=2.1.1
    - zc.lockfile
    - simplejson
    - routes >=2.3.1
    - pyopenssl
    - pywin32  # [win]

test:
  imports:
    - cherrypy
    - cherrypy.lib
    - cherrypy.process
    - cherrypy.scaffold
    - cherrypy.test
    - cherrypy.tutorial

  commands:
    - cherryd -h

about:
  home: http://www.cherrypy.org
  license: BSD 3-Clause
  license_file: LICENSE.md
  license_family: BSD
  summary: 'Object-Oriented HTTP framework'
  description: |
    CherryPy is a pythonic, object-oriented web framework.
    It allows developers to build web applications in much the same way they would
    build any other object-oriented Python program. This results in smaller source
    code developed in less time.
  dev_url: https://github.com/cherrypy/cherrypy
  doc_url: http://docs.cherrypy.org/en/latest
  doc_source_url: https://github.com/cherrypy/cherrypy/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - pmlandwehr
    - carlodri
