{% set version = "3.8.2" %}
package:
  name: cherrypy
  version: {{ version }}

source:
  fn: CherryPy-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/C/CherryPy/CherryPy-{{ version }}.tar.gz
  sha256: 423f0d459613604819e99ac4a55217d6bd0aaa9c970b92ba13a13aa17f21c65a

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - six

  run:
    - python
    - six

test:
  imports:
    - cherrypy
    - cherrypy.lib
    - cherrypy.process
    - cherrypy.scaffold
    - cherrypy.test
    - cherrypy.tutorial
    - cherrypy.wsgiserver

about:
  home: http://www.cherrypy.org
  license: BSD 3-Clause
  summary: 'Object-Oriented HTTP framework'

extra:
  recipe-maintainers:
    - pmlandwehr
