{% set name = "CherryPy" %}
{% set version = "11.0.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "5671f88c8dd8aecaac650761d18f74a2789b88a9337eb7433abe92a5e0be6780" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm

  run:
    - python
    - six
    - cheroot >=5.8.3
    - portend >=2.1.1
    - pypiwin32  # [win]    

test:
  imports:
    - cherrypy
    - cherrypy.lib
    - cherrypy.process
    - cherrypy.scaffold
    - cherrypy.test
    - cherrypy.tutorial
    - cherrypy.wsgiserver

  commands:
    - cherryd -h

about:
  home: http://www.cherrypy.org
  license: BSD 3-Clause
  license_file: cherrypy/LICENSE.txt
  license_family: BSD
  summary: 'Object-Oriented HTTP framework'
  dev_url: https://github.com/cherrypy/cherrypy
  doc_url: http://docs.cherrypy.org/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
