{% set name = "CherryPy" %}
{% set version = "18.0.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "405a284e891c487cc59f87112afaee03782cefe894bca15c853532bc8fc83a9b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - cherryd = cherrypy.__main__:run

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - six >=1.11.0
    - more-itertools
    - cheroot >=6.2.4
    - portend >=2.1.1
    - zc.lockfile
    - contextlib2
    - simplejson
    - routes >=2.3.1
    - pyopenssl
    - pywin32  # [win]

test:
  imports:
    - cherrypy
    - cherrypy.lib
    - cherrypy.process
    - cherrypy.scaffold
    - cherrypy.test
    - cherrypy.tutorial

  commands:
    - cherryd -h

about:
  home: http://www.cherrypy.org
  license: BSD 3-Clause
  license_file: LICENSE.md
  license_family: BSD
  summary: 'Object-Oriented HTTP framework'
  description: |
    CherryPy is a pythonic, object-oriented web framework.
    It allows developers to build web applications in much the same way they would
    build any other object-oriented Python program. This results in smaller source
    code developed in less time.
  dev_url: https://github.com/cherrypy/cherrypy
  doc_url: http://docs.cherrypy.org/en/latest
  doc_source_url: https://github.com/cherrypy/cherrypy/blob/master/docs/index.rst

extra:
  recipe-maintainers:
    - pmlandwehr
    - carlodri
