travis:
  secure:
    BINSTAR_TOKEN: OqnxVMVYx9JvPJGlBVFn+f9uKF63NgaaD6shzaoguOAAL8QkIJasGCkzzp+iNSesypJQ0qc7gRLMaoQXRVPV0IkfnrVzvvOg4KFLTrzR8mFr68TbfhaXXDw6TV738cIEA4DOouw+yx844UyIbeISnCc0MMsbXsVqIlOA+7goiqOQN0ER44JUbIWOI9TKbrnqTzyrWhQtmwi0Vn9UFfldQBLjkfUKOZQz1J1ZfGpfbuCNuHcslI9kJ1xMTz6eqX3H7qIXSbzRvW8ZdWHjJ50TDtWgPICkgBmtRNOm99594wqqhdpLZ7/absJagaDyuVcmjLKLZ1c04nkaHr0EG55JbvRZWms9TJqJI65rjFsSyJAfgM13q26RUk28T/+8TWY0tFNspaRbb+rAniD5tXEAL05RCfpirstLItQ8j/GZ9Oo3vcmQt5F0+KwM1dE0IJ4aFWatLpMtpxfFrD9xVmMVPgE/OVSr34vLVYbxf9MTkkgFjQXKj0uWGIwBly0aeLEdaJ0c2+FiEr7MesMLrLeXTXS5a6wFJcrR/VqQq9HW753xkzqnNxiyv5cn/NNY/wjXsIW7ePlfIpWsGFDQpDP5Cgx4ahakg1SwFZAb37C5q1ccToN/6DImna+339TC/vXdK4aHCLFaE8ETfodvGXB8vhWa/6KGYRzrnS7AILkshQ8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
